
// ── PROTOCOL DATA (condensed but complete) ─────────────────
function b(label,items){return'<div class="detail-block"><div class="block-label">'+label+'</div>'+items+'</div>'}
function ol(items){return'<ol class="step-list">'+items.map(function(x,i){return'<li><span class="step-num">'+(i+1)+'.</span><span>'+x+'</span></li>';}).join('')+'</ol>'}
function ul(items){return'<ul class="step-list">'+items.map(function(x){return'<li><span class="step-num">•</span><span>'+x+'</span></li>';}).join('')+'</ul>'}
function warn(t){return'<div class="callout callout-warn"><span class="callout-icon">⚠</span><span>'+t+'</span></div>'}
function key(t){return'<div class="callout callout-key"><span class="callout-icon">★</span><span>'+t+'</span></div>'}
function note(t){return'<div class="callout callout-note"><span class="callout-icon">📋</span><span>'+t+'</span></div>'}
function dose(drug,route,amt,n){return'<div class="dose-box"><div class="dose-drug">'+drug+'</div>'+(route?'<div class="dose-route">'+route+'</div>':'')+(amt?'<div class="dose-amount">'+amt+'</div>':'')+(n?'<div class="dose-note">'+n+'</div>':'')+'</div>';}

const SECTIONS={protocols:[
{section:"Universal Guidelines",icon:"📋",items:[
{id:"auth",title:"Authorization of Protocols",scope:"ALL",body:b("Standing Orders","<div class='block-text'><p>These protocols represent standing medical orders authorized by the Medical Director. Providers may implement standing orders when indicated and appropriate, prior to contact with Direct Medical Oversight.</p></div>")+b("Medical Director Responsibilities",ol(["Standing orders for ALS and BLS providers","Approval of all therapeutics, equipment, and supplies","Aspects of Indirect Medical Oversight for pre-hospital providers","Transport destination criteria","Practice parameters for pre-hospital medicine"]))},
{id:"vascular",title:"Vascular Access",scope:"AEMT/PM",body:b("Access Methods — Order of Preference",dose("Peripheral IV","","Including external jugular. First-line for most patients.","")+dose("Intraosseous (IO)","","Unstable patients or cardiac arrest. Sites: humeral head, proximal tibia, distal tibia.","")+dose("Pre-existing Central Access","","Unstable or arrest patients. Withdraw 5 mL prior to use to clear heparin lock.","")+dose("Dialysis AV Graft / Fistula","","LAST RESORT ONLY — after failed IV and IO attempts. Be prepared for hemorrhage.",''))},
{id:"medadmin",title:"Medication Administration & Verification",scope:"ALL",body:b("The Five Rights",warn("Medication Cross-Check MUST be performed prior to ANY medication: correct patient, medication, dose, route, time."))+b("Key Principles",ol(["No medication to a patient with known hypersensitivity","Never mix medications in same syringe","Hospital infusions may be continued; titration outside formulary requires written orders","Any IV medication may also be given IO","IM medications: lateral thigh preferred; deltoid acceptable","IN route: max 1 mL total (≤ 0.5 mL per nostril)","NEVER administer from an unlabeled syringe"]))+b("Pediatric Dosing","<div class='block-text'><p>Use Broselow Tape for length-based dosing. If patient exceeds tape length, use adult dosing.</p></div>")}
]},
{section:"General Medical",icon:"🩺",items:[
{id:"abdominal",title:"Abdominal Pain",scope:"ALL",body:b("Treatment",ol(["Manage airway as indicated","Establish vascular access as indicated","Normal saline as indicated","Analgesia per Pain Management Protocol","Ondansetron for nausea/vomiting as indicated","Treat shock as indicated","Allow position of comfort; knee/hip flexion may reduce pain"]))+b("Key Considerations",key("Abdominal or back pain in women of childbearing age — consider ectopic pregnancy until proven otherwise.")+key("Pain over 50 with abdominal/back pain, diminished lower extremity pulses, or shock — consider aortic aneurysm or dissection.")+key("Upper abdominal complaints in patients over 50, diabetics, or women — obtain 12-lead for cardiac etiology."))},
{id:"ams",title:"Altered Mental Status",scope:"ALL",body:b("Treatment Priority",ol(["Manage airway, position, O2 as indicated","Assess and correct blood glucose if hypoglycemic","Establish vascular access","12-lead EKG","Treat underlying cause: hypoxia, hypoglycemia, opioid toxicity, seizure, trauma"]))+b("AMS — Consider",note("AEIOU-TIPS: Alcohol/Arrhythmia, Epilepsy, Insulin, Overdose/Oxygen, Uremia — Trauma, Infection, Psychiatric, Stroke/Seizure/Shock"))},
{id:"anaphylaxis",title:"Anaphylaxis & Allergic Reaction",scope:"ALL",body:b("Immediate Treatment",warn("Epinephrine is FIRST-LINE for anaphylaxis. Do NOT delay for antihistamines.")+dose("Epinephrine (Anaphylaxis)","IM — Scope: EMT, AEMT, PM","Adult: 0.3 mg (1:1,000) IM lateral thigh — repeat every 5–15 min<br>Pediatric: 0.01 mg/kg (1:1,000) IM (max 0.3 mg) — repeat every 5 min","Auto-injector: 0.3 mg IM, repeat every 5 min"))+b("Adjuncts (After Epinephrine)",dose("Diphenhydramine","IV/IO/IM — Scope: PM","Adult: 50 mg — one dose only<br>Pediatric: 1 mg/kg (max 50 mg) — one dose only","")+dose("Methylprednisolone","IV or IM — Scope: PM","Adult: 125 mg IV or IM<br>Pediatric: 1–2 mg/kg IV or IM (max 125 mg)","Delayed benefit — administer early. NOT a substitute for epinephrine."))+b("Fluid Support",dose("Normal Saline","IV/IO — Scope: AEMT, PM","Adult: 500 mL bolus for hypotension — repeat as needed<br>Pediatric: 20 mL/kg bolus — repeat as needed",""))},
{id:"hypoglycemia",title:"Hypoglycemia",scope:"ALL",body:b("Treatment",warn("Blood glucose &lt; 60 mg/dL with symptoms — treat. Do not wait for loss of consciousness.")+dose("Oral Glucose (Conscious patient)","PO — Scope: EMT, AEMT, PM","One tube Instaglucose, cake frosting, candy, table sugar, honey, or non-diet soda. Repeat as needed.","")+dose("Dextrose 10% (D10)","IV/IO — Scope: AEMT, PM","Adult: Up to 25 g (250 mL) slow push/infusion — titrate to effect. Max 50 g total.<br>Pediatric (≥ 1 month): Up to 0.5 g/kg (5 mL/kg) — max single dose 25 g.",""))},
{id:"pain",title:"Pain Management",scope:"ALL",body:b("Non-Opioid First-Line",dose("Acetaminophen","PO: EMT, AEMT, PM | IV: AEMT, PM","Adult PO: 1,000 mg | Adult IV: 1,000 mg over 15 min<br>Pediatric PO: 15 mg/kg (max 1,000 mg) | Pediatric IV: 15 mg/kg over 15 min (max 1,000 mg)","")+dose("Ketorolac ★ NEW 2025","IV/IO or IM — Scope: PM","Adult IV/IO: 15–30 mg slow push over 1–2 min | Adult IM: 30 mg<br>Pediatric (≥ 2 yr): 0.5 mg/kg IV/IO or IM (max 15 mg) | Pediatric (&lt; 2 yr): Contact DMO","Single prehospital dose only — do not redose. Not for hemodynamic compromise."))+b("Opioid Analgesia",dose("Fentanyl","IV/IO/IM/IN — Scope: PM","Adult: 25–100 mcg — repeat every 5–10 min (max 200 mcg total)<br>Pediatric IV/IO/IM: 1 mcg/kg (max 100 mcg) — repeat every 5–10 min<br>Pediatric IN: 2 mcg/kg (max 100 mcg) — repeat every 10 min","Peak effect at 10 min IV — avoid rapid repeat dosing (stacking).")+dose("Ketamine (Sub-dissociative)","IV/IO infusion — Scope: PM","Adult: 20 mg in 100 mL NS over 5–10 min — may repeat ×1 after 10 min (max 40 mg total)","Alternative when fentanyl contraindicated or hemodynamically compromised."))},
{id:"behavioral",title:"Behavioral Emergency",scope:"ALL",body:b("Goals",ol(["Ensure scene and provider safety","Rule out medical cause for altered behavior","Safely transport for evaluation"]))+b("Chemical Sedation",dose("Midazolam (Agitation)","IV/IO/IM/IN — Scope: PM","Adult: 5–10 mg — repeat every 5 min (max 20 mg)<br>Pediatric: 0.1 mg/kg IV/IO/IM or 0.2 mg/kg IN (max 10 mg)",""))+warn("Always assess for hypoglycemia, hypoxia, and toxicology before attributing behavior to psychiatric cause.")},
{id:"nauseavomit",title:"Nausea & Vomiting",scope:"AEMT/PM",body:b("Treatment",dose("Isopropyl Alcohol (Inhaled)","Inhalation — Scope: EMT, AEMT, PM","Hold prep pad 1–2 cm below nares — have patient inhale deeply as frequently as needed. Patient must be able to self-administer.","")+dose("Ondansetron","IV/IO/IM or ODT — Scope: AEMT, PM","Adult: 4 mg — one dose only<br>Pediatric (&gt; 2 yr): 0.1 mg/kg (max 4 mg) — one dose only<br>Not indicated under age 2.","Monitor QT in patients with electrolyte abnormalities, CHF, or QT-prolonging medications."))},
{id:"hyperglycemia",title:"Hyperglycemia",scope:"ALL",body:b("Treatment",ol(["Manage airway as indicated","Establish vascular access; normal saline for dehydration","Adult NS bolus: 500 mL IV/IO — reassess; may repeat","Pediatric NS bolus: 20 mL/kg — reassess"])+key("Prehospital insulin is NOT indicated. Focus on fluid resuscitation and transport."))},
{id:"epistaxis",title:"Epistaxis",scope:"ALL",body:b("Treatment",ol(["Pinch nostrils firmly — sustained direct pressure for 10–15 minutes","Patient seated leaning forward (if possible) — reduces blood swallowing","Apply oxymetazoline topically if available","Do NOT have patient blow nose forcefully"])+warn("Posterior bleeds may not be visible externally — blood drains down the posterior pharynx. Monitor airway carefully."))}
]},
{section:"Cardiovascular",icon:"❤️",items:[
{id:"chestpain",title:"Chest Pain / ACS",scope:"ALL",body:b("Immediate Actions",ol(["12-lead EKG — acquire within first 5 min of contact","O2 only if SpO2 &lt; 94% — avoid hyperoxia","Establish vascular access","Continuous cardiac monitoring","Early notification to receiving facility"]))+b("Medications",dose("Aspirin","PO — Scope: EMT, AEMT, PM","Adult: 324 mg PO chewed<br>Pediatric: Not indicated","Contraindicated in hypersensitivity, active GI bleeding, hemophilia, intracranial hemorrhage.")+dose("Nitroglycerin","SL — Scope: AEMT, PM","Adult: 0.4 mg SL — repeat every 5 min as needed","Contraindicated: SBP &lt; 100, PDE5 inhibitors within 48 hr, inferior STEMI/suspected RV infarct, post-ROSC.")+dose("Fentanyl (for pain)","IV/IO/IM — Scope: PM","25–100 mcg — repeat every 5–10 min (max 200 mcg total)",""))+warn("STEMI identified on 12-lead: activate STEMI alert immediately. Transport to PCI-capable facility.")},
{id:"bradycardia",title:"Bradycardia",scope:"PM",body:b("Symptomatic Bradycardia",note("Symptomatic = hemodynamic compromise: hypotension, altered mentation, signs of shock, or severe angina.")+dose("Atropine","IV/IO — Scope: PM","Adult: 0.5 mg fast push — repeat every 3–5 min (max 3 mg)<br>Pediatric: 0.02 mg/kg IV/IO (min 0.1 mg; max 0.5 mg) — repeat ×1 in 3–5 min (max 3 mg total)","Ineffective in hypothermic bradycardia."))+b("If Unresponsive to Atropine",dose("Transcutaneous Pacing (TCP)","Scope: PM","Set rate 60–80 bpm. Increase mA until electrical capture. Confirm mechanical capture by pulse. Sedate with midazolam for conscious patients.",""))},
{id:"tachycardia",title:"Tachycardia / Dysrhythmias",scope:"PM",body:b("Unstable Tachycardia",dose("Synchronized Cardioversion","Scope: PM","Start 100 J for narrow complex; 200 J for wide complex or afib. Sedate prior if conscious: midazolam 2.5–5 mg IV/IO.",""))+b("Stable Narrow Complex (SVT)",note("Attempt vagal maneuvers first: Valsalva, carotid sinus massage, modified Valsalva technique.")+dose("Adenosine","IV — Scope: PM","Adult: 6 mg fast push — may repeat 12 mg ×1<br>Pediatric: 0.1 mg/kg (max 6 mg) fast push — may repeat 0.2 mg/kg (max 12 mg) ×1","Use most proximal site. Warn patient of transient asystole."))+b("VF / Pulseless VT — Antiarrhythmics",dose("Amiodarone OR Lidocaine","IV/IO — Scope: AEMT, PM","Amiodarone Adult: 300 mg — repeat 150 mg ×1<br>Amiodarone Pediatric: 5 mg/kg — repeat ×1<br>Lidocaine Adult: 1–1.5 mg/kg — repeat ×1 in 5 min<br>Lidocaine Pediatric: 1–1.5 mg/kg — repeat ×1","Use ONE agent only — do not combine amiodarone and lidocaine."))},
{id:"stroke",title:"Stroke",scope:"ALL",body:b("Cincinnati Stroke Screen","<ul class='step-list'><li><span class='step-num'>F</span><span><b>Facial droop</b> — Ask patient to smile. Is one side lower?</span></li><li><span class='step-num'>A</span><span><b>Arm drift</b> — Eyes closed, arms out 10 sec. Does one drift down?</span></li><li><span class='step-num'>S</span><span><b>Speech</b> — Repeat \"The sky is blue in Cincinnati.\" Slurred or wrong words?</span></li><li><span class='step-num'>T</span><span><b>Time</b> — Record last known well time. This drives tPA eligibility.</span></li></ul>"+warn("Last known well time is critical. Get this from patient, family, or bystander — document precisely."))+b("Treatment",ol(["Airway management as indicated","Oxygen only if SpO2 &lt; 94%","Blood glucose — treat hypoglycemia if &lt; 60 mg/dL","Establish vascular access","Do NOT lower blood pressure unless &gt; 220/120 — contact DMO","Early hospital notification: stroke alert with time, deficits, and last known well"]))},
{id:"syncope",title:"Syncope",scope:"ALL",body:b("Key Considerations",key("Exertional syncope or syncope with palpitations/chest pain warrants strong cardiac workup — transport regardless of recovery.")+key("12-lead EKG in all syncope patients — check for QT prolongation, Brugada pattern, WPW, heart block."))},
{id:"vad",title:"Ventricular Assist Devices (VAD)",scope:"PM",body:b("Key Points",warn("VAD patients may NOT have a palpable pulse — use MAP as the circulation marker. SpO2 and ETCO2 are valid monitoring tools.")+ol(["Do NOT attempt defibrillation unless the patient is confirmed pulseless VF","Contact VAD coordinator or receiving facility early","Assign one provider to continuously monitor femoral pulse","Maintain MAP &gt; 65 mmHg with fluids or norepinephrine per protocol"]))}
]},
{section:"Respiratory",icon:"🫁",items:[
{id:"mai-card",title:"Medication-Assisted Intubation (MAI)",scope:"PM",body:note("Full step-by-step procedure with weight-based calculator available in the <b>MAI tab</b> at the bottom of the screen.")},
{id:"airway",title:"Airway Management",scope:"ALL",body:b("Airway Sequence",ol(["Position, chin lift/jaw thrust, OPA/NPA","BVM with PEEP valve — O2 at 15 LPM","Supraglottic airway (King)","Orotracheal intubation — PM only","Cricothyrotomy — PM only, surgical airway of last resort"]))+b("MAI Key Agents",dose("Ketamine (Induction)","IV/IO","1–1.5 mg/kg over 1 min","")+dose("Vecuronium (Paralytic)","IV slow over 30–60 sec","0.1 mg/kg (typically 5–7 mg for average adult)","")+dose("Rocuronium (Paralytic — alt)","IV","0.5–1 mg/kg","")+warn("NMBA causes complete respiratory paralysis. Sedation/analgesia MUST be given before paralytic."))+b("Post-Intubation Targets","<ul class='step-list'><li><span class='step-num'>SpO2</span><span>94–98% (normoxia — avoid hyperoxia)</span></li><li><span class='step-num'>ETCO2</span><span>35–45 mmHg (normocarbia)</span></li><li><span class='step-num'>Rate</span><span>10–12 breaths/min adult; 12–20 pediatric</span></li></ul>")},
{id:"bronchospasm",title:"Bronchospasm / Asthma",scope:"ALL",body:b("Treatment",dose("Albuterol","Nebulized — Scope: EMT (own MDI), AEMT, PM","Adult: 2.5 mg/3 mL NS — repeat continuously as needed; or 8–10 puffs MDI<br>Pediatric: 2.5 mg/3 mL NS — repeat; or 4 puffs MDI","")+dose("Ipratropium","Nebulized — Scope: AEMT, PM","0.5 mg/2.5 mL combined with albuterol — repeat as needed<br>Do NOT use in children &lt; 2 yr with bronchiolitis.","")+dose("Methylprednisolone","IV or IM — Scope: PM","Adult: 125 mg IV or IM<br>Pediatric: 1–2 mg/kg (max 125 mg)","Delayed benefit — administer early.")+dose("Epinephrine (Refractory)","IM — Scope: PM","Adult: 0.3 mg (1:1,000) IM — repeat every 5–15 min",""))},
{id:"chf",title:"Pulmonary Edema / CHF",scope:"AEMT/PM",body:b("Treatment",ol(["Position upright (sitting) — reduces venous return","CPAP: 5–10 cmH2O — first-line for respiratory distress (All Levels)","Nitroglycerin — if SBP ≥ 100 and no contraindications"])+dose("Nitroglycerin","SL — Scope: AEMT, PM","0.4 mg SL — repeat every 5 min as tolerated (SBP ≥ 100)","Contraindicated: PDE5 inhibitors within 48 hr, RV infarct, post-ROSC."))},
{id:"cpap",title:"CPAP",scope:"ALL",body:b("Indications",ul(["Pulmonary edema / CHF","Asthma/COPD refractory to bronchodilators","Respiratory distress with SpO2 &lt; 90%"]))+b("Application",ol(["Starting pressure: 5 cmH2O — titrate to 10 cmH2O as tolerated","Patient must be alert and able to maintain mask seal","Monitor SpO2 and respiratory rate continuously"])+warn("Do NOT apply to patients who cannot protect airway, are vomiting, or are unresponsive.")+note("Scope: All Levels (EMT, AEMT, PM)"))}
]},
{section:"Cardiac Arrest",icon:"⚡",items:[
{id:"arrest",title:"Cardiac Arrest & Resuscitation",scope:"ALL",body:b("Core Sequence",ol(["High-quality CPR — minimize interruptions; target rate 100–120/min, depth 2–2.4 in adults","Defibrillate VF/pVT immediately — resume CPR immediately after shock","Vascular access — IO if IV not immediately available","Epinephrine every 3–5 min","Advanced airway — do not interrupt compressions more than 10 sec","Treat reversible causes: H's and T's"]))+b("Medications",dose("Epinephrine","IV/IO — Scope: AEMT, PM","Adult: 1 mg (1:10,000) every 3–5 min<br>Pediatric: 0.01 mg/kg (1:10,000) (max 1 mg) every 3–5 min","")+dose("Amiodarone or Lidocaine (refractory VF/pVT)","IV/IO — Scope: AEMT, PM","Amiodarone Adult: 300 mg → repeat 150 mg<br>Lidocaine Adult: 1–1.5 mg/kg → repeat ×1 in 5 min<br>Use ONE agent — do not combine.","")+dose("Calcium Chloride (suspected hyperkalemia)","IV/IO — Scope: PM","Adult: 1 g push (DMO for repeat)<br>Pediatric: 20 mg/kg push (max 1 g)",""))+b("H's and T's","<ul class='step-list'><li><span class='step-num'>H</span><span>Hypovolemia, Hypoxia, Hydrogen ion (acidosis), Hypo/Hyperkalemia, Hypothermia</span></li><li><span class='step-num'>T</span><span>Tension pneumo, Tamponade, Toxins, Thrombosis (PE/STEMI)</span></li></ul>")},
{id:"postrosc",title:"Post-ROSC Care",scope:"PM",body:b("Targets",warn("NORMOXIA and NORMOCARBIA are the targets. Both hyperoxia and hyperventilation independently worsen neurologic outcomes.")+"<ul class='step-list'><li><span class='step-num'>SpO2</span><span>94–98% — Do NOT target 100%</span></li><li><span class='step-num'>ETCO2</span><span>35–45 mmHg — Do NOT hyperventilate</span></li><li><span class='step-num'>SBP</span><span>≥ 90 mmHg adult; age-appropriate pediatric</span></li></ul>")+b("Post-ROSC Treatment",ol(["12-lead EKG immediately — activate STEMI alert if identified","Blood glucose — treat hypoglycemia with D10 if &lt; 60","Treat seizures: midazolam 5 mg IV/IO/IM","Hypotension: NS 500 mL bolus → norepinephrine infusion"])+dose("Norepinephrine (post-ROSC hypotension)","IV/IO infusion — Scope: PM","Adult: 0.1–0.2 mcg/kg/min — titrate to MAP &gt; 65 mmHg<br>Pediatric: 0.1 mcg/kg/min — titrate to age-appropriate BP<br>Admixture: 4 mg in 500 mL NS = 8 mcg/mL",""))},
{id:"tor",title:"Termination of Resuscitation",scope:"PM",body:b("Field TOR — All Criteria Required",ol(["High-quality CPR throughout","Appropriate oxygenation/ventilation applied","Vascular access achieved","Defibrillation and rhythm-appropriate medications given","Min 25 min EMS resuscitation (UNWITNESSED) or 40 min (WITNESSED)","At least 5 min since last epinephrine dose","No ROSC at any point","No refractory or recurrent VF/VT","No neurological activity","Persistent asystole, agonal rhythm, or slow wide-complex PEA","Reversible causes identified and managed when possible","If minor: parent/guardian agrees to discontinuing efforts","All EMS providers agree TOR is appropriate"])+key("ETCO2 &lt; 10 mmHg or falling &gt; 25% despite resuscitation is poor prognostic indicator — supporting evidence for TOR, not standalone criteria."))},
{id:"dod",title:"Determination of Death",scope:"ALL",body:b("Withhold Resuscitation — Without DMO",note("Does NOT apply to: lightning/electrocution, drowning, hypothermia — resuscitate regardless.")+ul(["Decapitation","Decomposition or putrefaction","Transection of torso","Incineration (&gt; 90% BSA full-thickness burns)","Injuries clearly incompatible with life","Blunt/penetrating trauma: apneic, pulseless, no signs of life on arrival","Non-traumatic arrest with obvious dependent lividity or rigor mortis","Valid DNR / TPOPP present"]))}
]},
{section:"Trauma",icon:"🩹",items:[
{id:"trauma",title:"Universal Trauma Management",scope:"ALL",body:b("XABCDE Primary Survey",warn("Scene time goal: under 10 minutes for unstable patients or those likely to need surgical intervention.")+"<ul class='step-list'><li><span class='step-num'>X</span><span><b>Exsanguinating hemorrhage</b> — control first. Tourniquet 2–3 in proximal to wound, not over joint.</span></li><li><span class='step-num'>A</span><span><b>Airway</b> — assess patency, manage threats</span></li><li><span class='step-num'>B</span><span><b>Breathing</b> — assess rate/symmetry. Target SpO2 94–98%. Tension pneumo → needle decompression.</span></li><li><span class='step-num'>C</span><span><b>Circulation</b> — NS bolus adult 500 mL, peds 20 mL/kg if SBP below thresholds</span></li><li><span class='step-num'>D</span><span><b>Disability</b> — GCS/AVPU, gross motor exam, herniation signs</span></li><li><span class='step-num'>E</span><span><b>Exposure</b> — full body exam, roll for back, prevent hypothermia</span></li></ul>")},
{id:"tbi",title:"Head Injury / TBI",scope:"ALL",body:b("Blood Pressure Targets","<ul class='step-list'><li><span class='step-num'>Adult</span><span>SBP ≥ 110 mmHg</span></li><li><span class='step-num'>&lt; 1 mo</span><span>&gt; 60 mmHg</span></li><li><span class='step-num'>1–12 mo</span><span>&gt; 70 mmHg</span></li><li><span class='step-num'>1–10 yr</span><span>&gt; 70 + (age × 2) mmHg</span></li></ul>"+warn("Do NOT hyperventilate — causes cerebral vasoconstriction. ETCO2 target: 35–45 mmHg.")+warn("CONTROLLED hyperventilation (ETCO2 30–35) ONLY for signs of impending herniation: blown pupil, posturing, Cushing's response."))},
{id:"burns",title:"Burns — Thermal",scope:"ALL",body:b("Treatment",ol(["Stop burning process — remove from source, remove burning clothing","Remove constricting bands (watches, rings)","High-flow O2 for enclosed space or CO concern","Early airway if face/airway involved — progressive edema can cause complete obstruction","Fluids ONLY if in shock — do not over-resuscitate","Cover with dry clean dressings — no gels, ointments, or ice","Prevent hypothermia"])+dose("Hydroxocobalamin (cyanide — enclosed space)","IV/IO — Scope: PM","Adult: 5 g over 15 min<br>Pediatric: 70 mg/kg over 15 min (max 5 g)","For AMS, respiratory distress, shock, or seizures in enclosed-space fire."))+b("Rule of Nines (Adults)","<ul class='step-list'><li><span class='step-num'>9%</span><span>Head and neck</span></li><li><span class='step-num'>9%</span><span>Each arm (entire)</span></li><li><span class='step-num'>18%</span><span>Anterior trunk</span></li><li><span class='step-num'>18%</span><span>Posterior trunk</span></li><li><span class='step-num'>18%</span><span>Each leg (entire)</span></li><li><span class='step-num'>1%</span><span>Perineum/genitalia</span></li></ul>"+note("Only 2nd and 3rd degree burns count for TBSA. 1st degree not included."))},
{id:"hem",title:"Extremity Trauma & Hemorrhage Control",scope:"ALL",body:b("Hemorrhage Priority Sequence",ol(["Direct pressure with pressure dressing","Commercial tourniquet: 2–3 in proximal to wound, not over joint — tighten until bleeding stops AND distal pulse eliminated","Second tourniquet if first insufficient — proximal to first","Junctional wounds: hemostatic gauze packing + direct pressure"])+warn("Mark tourniquet time prominently on patient. Do NOT remove in amputation, unstable multi-trauma, or unstable clinical situation."))+b("Amputation Note",key("KU Medical Center is the only Kansas regional center performing peripheral amputation replantation. Transport stable isolated amputations there."))},
{id:"spinal",title:"Spinal Motion Restriction (SMR)",scope:"ALL",body:b("Apply SMR If ANY Present",ul(["Midline neck or spine pain/tenderness on palpation","Altered mental status with concerning mechanism","Focal neurologic deficit","Evidence of alcohol or drug intoxication with concerning mechanism","Severe or painful distracting injury","Communication barrier with concerning mechanism"])+warn("NO SMR for penetrating neck trauma — associated with increased mortality. No collar, no board."))+b("Transport",key("Do NOT transport routinely on rigid long boards. Remove as soon as practical. Ambulatory patients do not require a spine board."))}
]},
{section:"Environmental & Toxicology",icon:"☣️",items:[
{id:"opioid",title:"Opioid Overdose",scope:"ALL",body:b("Treatment",ol(["Airway — position, BVM ventilation","Naloxone — titrate to adequate respirations, not full wakefulness"])+dose("Naloxone","IV/IO/IM/IN — Scope: EMT (auto/nasal), AEMT, PM","Adult Titrated: 0.4–2 mg — repeat every 3–5 min (max 4 mg)<br>Auto/nasal: per device — repeat every 5 min<br>Pediatric: 0.01 mg/kg (max 0.4 mg) — repeat every 3–5 min<br>High-potency opioids: up to 4 mg per dose with frequent redosing","")+warn("Naloxone duration (30–90 min) is SHORTER than most opioids (4+ hr). All patients receiving naloxone must be transported."))},
{id:"co",title:"Carbon Monoxide Poisoning",scope:"ALL",body:b("Treatment",ol(["Remove from exposure","High-flow O2 via non-rebreather at 15 LPM — continue until symptoms resolve or hospital arrival","Manage airway as indicated; intubate if GCS ≤ 8","IV access, cardiac monitoring, 12-lead EKG"])+warn("Pulse oximetry is UNRELIABLE in CO poisoning — reads falsely normal. SpO2 does not indicate adequate O2 delivery."))},
{id:"hypothermia",title:"Hypothermia",scope:"ALL",body:b("Classification","<ul class='step-list'><li><span class='step-num'>Mild</span><span>32–35°C (90–95°F): shivering, confusion</span></li><li><span class='step-num'>Moderate</span><span>28–32°C (82–90°F): absent shivering, paradoxical undressing</span></li><li><span class='step-num'>Severe</span><span>&lt; 28°C (&lt; 82°F): coma, cardiac arrest risk</span></li></ul>")+b("Treatment",ol(["Remove wet clothing — handle gently (cold myocardium is irritable)","Passive rewarming: blankets, warm environment","Warm IV fluids if available and vascular access achieved","Cardiac monitoring — monitor for VF"])+warn('"Not dead until warm and dead" — resuscitation should not be terminated for hypothermic arrest until rewarmed at hospital.')+note("Atropine is ineffective in hypothermic bradycardia."))},
{id:"tca",title:"Tricyclic Antidepressant Overdose",scope:"PM",body:b("Recognition",ul(["QRS widening &gt; 100 ms","Hypotension","AMS, seizures","Anticholinergic signs: dry skin, tachycardia, mydriasis, urinary retention"]))+b("Treatment",dose("Sodium Bicarbonate (QRS &gt; 100 ms)","IV/IO — Scope: PM","Adult: 1 mEq/kg push<br>Pediatric: 1 mEq/kg push<br>DMO required for non-arrest or repeat dosing","Targets QRS narrowing and hemodynamic stabilization.")+dose("Midazolam (seizures)","IV/IO/IM — Scope: PM","Adult: 5 mg IV — repeat 5 mg every 5 min (max 20 mg)","")+warn("Avoid phenytoin — not effective for TCA-induced seizures. Do NOT give flumazenil if benzodiazepines co-ingested."))}
]},
{section:"Obstetrics",icon:"👶",items:[
{id:"ob",title:"OB / Gynecological Emergencies",scope:"ALL",body:b("Key Assessments",ul(["Gestational age (LMP or stated weeks)","Bleeding: amount, color, clots, duration","Pain: onset, severity, location, character","Fetal movement history"])+key("Ectopic pregnancy: pain + vaginal bleeding + hemodynamic instability in woman of childbearing age = ectopic until proven otherwise."))+b("Transport Position",note("After 20 weeks gestation: left lateral decubitus or manual left uterine displacement to relieve aortocaval compression."))},
{id:"delivery",title:"Field Delivery",scope:"ALL",body:b("Delivery",ol(["Support perineum; guide head with gentle pressure — do not pull","Check for nuchal cord — gently slip over head or clamp and cut if cannot slip","Guide anterior shoulder downward, then posterior shoulder upward","Clamp cord in 2 places, cut between clamps","Dry and stimulate newborn; keep warm"]))+b("Shoulder Dystocia",warn("McRoberts maneuver: hyperflexion of maternal thighs onto abdomen. Suprapubic pressure (not fundal). Do NOT apply pressure to fundus."))},
{id:"eclampsia",title:"Pre-Eclampsia & Eclampsia",scope:"PM",body:b("Recognition",ul(["Pre-eclampsia: SBP ≥ 140 or DBP ≥ 90 after 20 weeks + proteinuria","Eclampsia: seizure in pre-eclamptic patient","Symptoms: headache, visual changes, epigastric pain, facial edema"]))+b("Treatment",dose("Magnesium Sulfate (seizure prevention/control)","IV rapid infusion — Scope: PM (Extended Formulary)","4 g rapid infusion (4 g in 50 mL D5W — macro drip at 2 gtts/sec) — may repeat once at 2 g","Calcium Chloride 1 g must be immediately available as antidote for hypermagnesemia.")+dose("Midazolam (active eclamptic seizure)","IV/IO/IM — Scope: AEMT (seizure), PM","5 mg IV — repeat 5 mg every 5 min (max 20 mg)",""))}
]},
{section:"Pediatric",icon:"🧒",items:[
{id:"bronchiolitis",title:"Bronchiolitis",scope:"ALL",body:b("Treatment",ol(["Positioning — upright or slight head elevation","Supplemental O2 for SpO2 &lt; 94%","Suction nares if secretions obstructing airway (BLS)","Albuterol trial — only if there is a clinical response"])+warn("Do NOT administer ipratropium to children &lt; 2 years with bronchiolitis."))},
{id:"neonate",title:"Neonate Resuscitation",scope:"ALL",body:b("Initial Steps",ol(["Dry and stimulate — 30 seconds to determine status","Keep warm — hypothermia worsens outcomes rapidly","Position airway — slight neck extension ('sniffing position')","Clear secretions by suction if visible or airway obstructed"]))+b("Assessment — 1 Min","<ul class='step-list'><li><span class='step-num'>HR &gt; 100</span><span>Monitor, support as needed</span></li><li><span class='step-num'>HR 60–100</span><span>PPV at 40–60 breaths/min</span></li><li><span class='step-num'>HR &lt; 60</span><span>CPR (3:1 ratio) + PPV</span></li></ul>"+dose("Epinephrine (Neonatal Arrest)","IV (umbilical vein) or IO — Scope: PM","0.01–0.03 mg/kg (1:10,000) IV/IO",""))},
{id:"brue",title:"BRUE — Brief Resolved Unexplained Event",scope:"ALL",body:b("Definition","<div class='block-text'><p>In infant &lt; 1 year: sudden, brief (&lt; 1 min), now resolved episode of one or more: cyanosis/pallor, absent/irregular/decreased breathing, marked change in tone, altered responsiveness.</p></div>")+b("Treatment",ol(["Full assessment — vital signs, SpO2, blood glucose","Treat hypoglycemia if present","All BRUE patients require hospital transport for evaluation"])+key("BRUE may be the presenting sign of a cardiac arrhythmia, airway anomaly, or NAT. Transport all cases."))}
]},
{section:"Clinical Policies",icon:"📜",items:[
{id:"refusal",title:"Patient Refusals",scope:"ALL",body:b("Competent Refusal Requirements",ol(["Patient is adult or emancipated minor","Patient has decision-making capacity: understands condition, risks of refusal, and alternatives","No evidence of intoxication, AMS, or impaired judgment"])+warn("Document thoroughly: mental status, capacity assessment, information provided, and patient's stated reasoning. Offer transport again before leaving."))},
{id:"restraints",title:"Physical Restraints",scope:"ALL",body:b("Principles",ol(["Restraints are a last resort after de-escalation attempts","Use minimum force necessary","Restrained patients must be continuously monitored for respiratory and circulatory compromise","Document clinical justification, methods used, and monitoring performed"])+warn("Prone restraint is PROHIBITED. Never restrain face down. Monitor airway and ventilation continuously. Positional asphyxia is a real risk."))}
]}
]};

const FORMULARY=[
{name:"Acetaminophen",cls:"Analgesic, Antipyretic",scope:"PO: ALL | IV: AEMT, PM",dose:"Adult PO: 1,000 mg | Adult IV: 1,000 mg over 15 min | Peds PO: 15 mg/kg (max 1,000 mg) | Peds IV: 15 mg/kg over 15 min",ci:"Hypersensitivity, known chronic liver disease, >3 g in past 24 hr",warn:"Determine prior acetaminophen intake. Chronic supratherapeutic use causes hepatotoxicity."},
{name:"Adenosine",cls:"Antidysrhythmic",scope:"PM",dose:"Adult: 6 mg fast push — repeat 12 mg ×1 | Peds: 0.1 mg/kg (max 6 mg) — repeat 0.2 mg/kg (max 12 mg) ×1",ci:"2nd/3rd degree AV block, sick sinus, confirmed afib/flutter, hypersensitivity",warn:"Reduce dose 50% for heart transplant or central line. Expect transient asystole — warn patient."},
{name:"Albuterol",cls:"Short-acting beta-2 agonist",scope:"EMT (own MDI), AEMT, PM",dose:"Bronchospasm Adult: 2.5 mg/3 mL NS neb or 8–10 puffs MDI | Peds: 2.5 mg/3 mL NS or 4 puffs | Hyperkalemia: 2.5 mg/3 mL NS continuously (max 8 doses adult, 4 doses peds)",ci:"Hypersensitivity",warn:"Caution with hypokalemia, tachycardia, CAD, hypertension, arrhythmia."},
{name:"Amiodarone",cls:"Class III antidysrhythmic",scope:"AEMT, PM",dose:"Adult: 300 mg IV/IO → repeat 150 mg ×1 | Peds: 5 mg/kg → repeat ×1",ci:"Hypersensitivity",warn:"Equivalent to lidocaine for refractory VF/VT. Use ONE agent — do not combine."},
{name:"Aspirin",cls:"Antiplatelet, NSAID",scope:"EMT, AEMT, PM",dose:"Adult: 324 mg PO chewed | Peds: not indicated",ci:"Hypersensitivity, active GI bleeding, thrombocytopenia, hemophilia, intracranial hemorrhage",warn:"Minimal side effects with single dose. Administer for ACS suspicion."},
{name:"Atropine",cls:"Anticholinergic",scope:"PM",dose:"Bradycardia Adult: 0.5 mg fast push — repeat every 3–5 min (max 3 mg) | Peds: 0.02 mg/kg (min 0.1; max 0.5 mg) ×2 | OP/Nerve agent Adult: 2 mg IM — repeat every 5 min until secretions dry (no max)",ci:"None absolute in emergencies",warn:"Ineffective in hypothermic bradycardia. Titrate to drying of secretions — NOT heart rate — for OP toxicity."},
{name:"Calcium Chloride",cls:"Antidote, calcium salt",scope:"PM (DMO for non-arrest/repeat)",dose:"Adult arrest: 1 g push | Adult with pulse: 1 g over 5 min (DMO) | Peds: 20 mg/kg (max 1 g)",ci:"Hypercalcemia, hypersensitivity",warn:"Severe tissue necrosis with extravasation. Flush before/after — do NOT push with sodium bicarb in same line."},
{name:"Dextrose 10% (D10)",cls:"Glucose-elevating agent",scope:"AEMT, PM",dose:"Adult: up to 25 g (250 mL) — titrate; max 50 g | Peds ≥1 mo: 0.5 g/kg (5 mL/kg) — max 25 g per dose",ci:"Hyperglycemia",warn:"Use large patent vein — irritating with extravasation. DMO before giving to pediatric patient on ketogenic diet."},
{name:"Diphenhydramine",cls:"Antihistamine (H1)",scope:"PM",dose:"Adult: 50 mg IV/IO/IM — one dose | Peds: 1 mg/kg (max 50 mg) — one dose",ci:"Hypersensitivity, premature infants/neonates",warn:"Do NOT give before epinephrine in anaphylaxis. Epi is always first."},
{name:"Epinephrine",cls:"Alpha/beta adrenergic agonist",scope:"Arrest: AEMT, PM | Anaphylaxis: EMT, AEMT, PM | Refractory asthma: PM",dose:"Arrest Adult: 1 mg (1:10,000) every 3–5 min | Arrest Peds: 0.01 mg/kg (max 1 mg) every 3–5 min | Anaphylaxis Adult: 0.3 mg (1:1,000) IM — repeat every 5–15 min | Anaphylaxis Peds: 0.01 mg/kg (max 0.3 mg) IM",ci:"None absolute in life-threatening emergencies",warn:"NEVER IV for anaphylaxis — use IM. Never after ROSC without vasopressor context."},
{name:"Fentanyl",cls:"Synthetic opioid analgesic",scope:"PM",dose:"Adult: 25–100 mcg IV/IO/IM/IN — repeat every 5–10 min (max 200 mcg total) | Peds IV/IO/IM: 1 mcg/kg (max 100 mcg) — repeat every 5–10 min | Peds IN: 2 mcg/kg (max 100 mcg) — repeat every 10 min",ci:"Hypersensitivity to fentanyl",warn:"Peak effect at 10 min IV — avoid rapid repeat dosing (stacking). Lower doses for ≥65, debilitated, critically ill."},
{name:"Hydromorphone (Dilaudid)",cls:"Opioid analgesic agonist",scope:"PM",dose:"Adult: 0.5–2 mg IV/IO every 10 min (max 4 mg total). May give IM. | Peds: Contact DMO",ci:"Hypersensitivity, status asthmaticus, opioid addiction (relative)",warn:"5–10× more potent than morphine by weight. Increased ICP, MAOIs can cause serious reactions."},
{name:"Ipratropium",cls:"Anticholinergic bronchodilator",scope:"AEMT, PM",dose:"0.5 mg/2.5 mL combined with albuterol — repeat as needed. Do NOT use in children <2 yr with bronchiolitis.",ci:"Hypersensitivity to ipratropium, atropine, or derivatives",warn:"May worsen angle-closure glaucoma."},
{name:"Isopropyl Alcohol (Inhaled)",cls:"Antiemetic (inhaled)",scope:"EMT, AEMT, PM",dose:"Hold prep pad 1–2 cm below nares — inhale deeply as frequently as needed. Patient must self-administer.",ci:"Patient unable to self-administer. Avoid in pregnancy.",warn:""},
{name:"Ketamine",cls:"Dissociative anesthetic",scope:"PM",dose:"Analgesia Adult: 20 mg in 100 mL NS over 5–10 min — repeat ×1 after 10 min (max 40 mg total) | MAI Induction: 1–1.5 mg/kg IV over 1 min",ci:"Hypersensitivity, ACS, CVA, active psychosis",warn:"Caution with severe hypertension. May cause increased secretions — have suction available."},
{name:"Ketorolac (Toradol) ★ NEW 2025",cls:"NSAID, Analgesic",scope:"PM",dose:"Adult IV/IO: 15–30 mg slow push over 1–2 min | Adult IM: 30 mg | Peds ≥2 yr: 0.5 mg/kg (max 15 mg) IV/IO or IM | Peds <2 yr: DMO | Single prehospital dose only — do not redose",ci:"Active GI bleeding/ulceration, NSAID hypersensitivity, coagulopathy, significant renal impairment, hypotension/shock, pregnancy (esp. 3rd trimester)",warn:"Do NOT use in hemodynamic compromise or active hemorrhage. Single dose only. Do not combine with other NSAIDs.",isNew:true},
{name:"Lidocaine",cls:"Class Ib antidysrhythmic",scope:"Arrest: AEMT, PM | Sustained VT: PM | IO analgesia: AEMT, PM",dose:"Arrest Adult: 1–1.5 mg/kg — repeat ×1 in 5 min | Peds arrest: 1–1.5 mg/kg — repeat ×1 | IO analgesia Adult: 40 mg slow push → 10 mL NS fast → 20 mg slow | IO analgesia Peds: 0.5 mg/kg (max 40 mg) slow → 5 mL NS → 0.25 mg/kg slow",ci:"Hypersensitivity to amide anesthetics, Adams-Stokes, AV block without pacemaker, WPW",warn:"Toxicity: seizures, AMS, slurred speech, tinnitus, visual disturbances. Equivalent to amiodarone — use one only."},
{name:"Magnesium Sulfate",cls:"Electrolyte, anticonvulsant (Extended Formulary)",scope:"PM",dose:"Eclampsia: 4 g rapid infusion (4 g in 50 mL D5W at 2 gtts/sec) — repeat ×1 at 2 g | Torsades/VF: 1–2 g rapid infusion | Asthma Adult: 2 g in 50–100 mL NS/D5W over 10–20 min | Asthma Peds: 20–50 mg/kg over 10–20 min",ci:"Renal impairment (caution). Do not give within 2 hr of delivery in eclampsia.",warn:"Hypermagnesemia signs: flushing, hypotension, reflex loss, paralysis. Calcium Chloride must be immediately available as antidote."},
{name:"Methylprednisolone",cls:"Glucocorticoid, corticosteroid",scope:"PM",dose:"Adult: 125 mg IV or IM | Peds: 1–2 mg/kg IV or IM (max 125 mg)",ci:"Hypersensitivity, systemic fungal infections, premature infants",warn:"Delayed benefit — administer early. NOT a substitute for epinephrine in anaphylaxis."},
{name:"Midazolam",cls:"Benzodiazepine",scope:"Seizure (AEMT): 10 mg IM only | All other: PM",dose:"Seizure Adult no IV: 10 mg IM — repeat 5 mg every 5 min (max 20 mg) | Seizure Adult IV: 5 mg — repeat every 5 min (max 20 mg) | Agitation: 5–10 mg IV/IO/IM/IN — repeat every 5 min (max 20 mg) | Peds seizure (<13 kg): 0.1 mg/kg IV or 0.2 mg/kg IN (max 10 mg) | Peds seizure (13–40 kg) no IV: 5 mg IM | MAI maintenance: 2.5–5 mg every 10–30 min",ci:"Documented hypersensitivity",warn:"May cause respiratory arrest. Lower doses for ≥65 or debilitated. IN may take 10 min for full effect."},
{name:"Morphine",cls:"Opioid analgesic (Extended Formulary)",scope:"PM",dose:"Adult: 2–10 mg IV slowly — repeat small increments every 5 min (max 20 mg pain; max 30 mg over 20 min for burns). Also IM or SQ.",ci:"Volume depletion/hypotension, head trauma, acute asthma, hypersensitivity",warn:"Caution in ACS — may reduce P2Y12 inhibitor efficacy. Potentiated by alcohol, antihistamines, sedatives."},
{name:"Naloxone",cls:"Opioid reversal agent",scope:"EMT (auto/nasal), AEMT, PM",dose:"Adult Titrated: 0.4–2 mg every 3–5 min (max 4 mg) | Auto/nasal: per device every 5 min | Peds: 0.01 mg/kg (max 0.4 mg) every 3–5 min | High-potency opioids: up to 4 mg per dose with frequent redosing",ci:"Hypersensitivity",warn:"Duration (30–90 min) SHORTER than most opioids. All naloxone patients must be transported. Sudden reversal precipitates withdrawal."},
{name:"Nitroglycerin",cls:"Nitrate, anti-anginal",scope:"AEMT, PM",dose:"Adult: 0.4 mg SL — repeat every 5 min as needed | Peds: Not routine — DMO",ci:"Hypersensitivity to nitrates, PDE5 inhibitors within 48 hr, SBP <100 or ≥30 below baseline, extreme bradycardia (<50 bpm), post-ROSC",warn:"NEVER after ROSC. EXTREME CAUTION in inferior STEMI or suspected RV infarction."},
{name:"Norepinephrine",cls:"Alpha/beta agonist — vasopressor",scope:"PM",dose:"Adult: 0.1–0.2 mcg/kg/min — titrate to SBP >90 or MAP >65 | Admixture: 4 mg in 500 mL NS = 8 mcg/mL | Peds: 0.1 mcg/kg/min — titrate",ci:"Hypersensitivity, uncorrected volume deficit, peripheral vascular thrombosis (except life-saving)",warn:"VESICANT — severe tissue necrosis with extravasation. Use largest most proximal vein. Confirm patency before starting."},
{name:"Normal Saline (0.9% NaCl)",cls:"Crystalloid IV fluid",scope:"IV/IO: AEMT, PM | Flush: EMT per protocol",dose:"Adult bolus: 250–500 mL — repeat as indicated | Crush syndrome: 500–1,000 mL/hr (DMO) | Flush: 5–10 mL after each med | Peds ≥1 mo bolus: 20 mL/kg — repeat | Peds <1 mo: 10 mL/kg — repeat",ci:"None",warn:""},
{name:"Ondansetron",cls:"Antiemetic, 5-HT3 antagonist",scope:"AEMT, PM",dose:"Adult: 4 mg IV/IO/IM or ODT — one dose | Peds >2 yr: 0.1 mg/kg (max 4 mg) — one dose | Not indicated <2 yr",ci:"Hypersensitivity, age <2 years",warn:"QT prolongation risk — avoid in congenital long QT or QT-prolonging medications. ECG in high-risk patients."},
{name:"Oral Glucose / Instaglucose",cls:"Glucose-elevating agent (oral)",scope:"EMT, AEMT, PM",dose:"One tube Instaglucose, cake frosting, candy, table sugar, honey, non-diet soda — repeat as needed",ci:"Hyperglycemia, patient unable to swallow or protect airway",warn:"DMO before giving to peds patient on ketogenic diet with chronic seizures."},
{name:"Rocuronium",cls:"Non-depolarizing NMBA (Extended Formulary)",scope:"PM only",dose:"0.5–1 mg/kg IV",ci:"Hypersensitivity",warn:"COMPLETE RESPIRATORY PARALYSIS. Sedation/analgesia MUST precede. May store at room temp up to 60 days. Reversed by sugammadex (not prehospital)."},
{name:"Sodium Bicarbonate",cls:"Alkalinizing agent, antidote",scope:"PM (DMO for non-arrest/repeat)",dose:"Adult arrest: 1 mEq/kg IV/IO push | Adult with pulse: 1 mEq/kg over 5 min (DMO) | Peds: same weight-based dosing",ci:"Hypersensitivity, severe pulmonary edema, known alkalosis, hypernatremia, hypokalemia",warn:"Do NOT mix with other drugs — flush before/after. Bicarb generates CO2 — increase ventilation and monitor ETCO2."},
{name:"Vecuronium",cls:"Non-depolarizing NMBA",scope:"PM only",dose:"Adult and Peds >16 yr: 0.1 mg/kg IV slow over 30–60 sec (typically 5–7 mg for average adult)",ci:"Hypersensitivity",warn:"COMPLETE RESPIRATORY PARALYSIS. Sedation/analgesia MUST precede. Patient is fully conscious without it."}
];

const SCOPE_DATA={
airway:[{skill:"Chin lift / Jaw thrust",emt:1,aemt:1,pm:1},{skill:"NPA Insertion",emt:1,aemt:1,pm:1},{skill:"OPA Insertion",emt:1,aemt:1,pm:1},{skill:"Suction — Upper Airway",emt:1,aemt:1,pm:1},{skill:"Suction — Trachea/Stoma",emt:0,aemt:0,pm:1},{skill:"Nasal Cannula / NRB Mask",emt:1,aemt:1,pm:1},{skill:"BVM with PEEP Valve",emt:1,aemt:1,pm:1},{skill:"ETCO2 Monitoring",emt:1,aemt:1,pm:1},{skill:"CPAP",emt:1,aemt:1,pm:1},{skill:"Supraglottic Airway (King)",emt:1,aemt:1,pm:1},{skill:"Orotracheal Intubation",emt:0,aemt:0,pm:1},{skill:"Cricothyrotomy",emt:0,aemt:0,pm:1},{skill:"Needle Decompression — Chest",emt:0,aemt:0,pm:1},{skill:"Ventilator Management",emt:0,aemt:0,pm:1}],
circulation:[{skill:"CPR",emt:1,aemt:1,pm:1},{skill:"Mechanical Compression Device",emt:1,aemt:1,pm:1},{skill:"AED",emt:1,aemt:1,pm:1},{skill:"Manual Defibrillation",emt:0,aemt:1,pm:1},{skill:"12-Lead EKG Acquisition",emt:1,aemt:1,pm:1},{skill:"12-Lead EKG Interpretation",emt:0,aemt:0,pm:1},{skill:"Limb Lead Interpretation",emt:0,aemt:1,pm:1},{skill:"Transcutaneous Pacing",emt:0,aemt:0,pm:1},{skill:"Synchronized Cardioversion",emt:0,aemt:0,pm:1}],
vascular:[{skill:"Peripheral IV",emt:0,aemt:1,pm:1},{skill:"External Jugular IV",emt:0,aemt:0,pm:1},{skill:"Intraosseous (IO)",emt:0,aemt:1,pm:1},{skill:"Pre-existing Central Line Access",emt:0,aemt:0,pm:1},{skill:"Dialysis AV Graft / Fistula (last resort)",emt:0,aemt:0,pm:1}],
meds:[{skill:"Oral (PO)",emt:1,aemt:1,pm:1},{skill:"Sublingual (SL)",emt:1,aemt:1,pm:1},{skill:"Inhalation / Nebulized",emt:1,aemt:1,pm:1},{skill:"Intramuscular (IM)",emt:1,aemt:1,pm:1},{skill:"Intranasal (IN)",emt:1,aemt:1,pm:1},{skill:"Intravenous (IV) Push",emt:0,aemt:1,pm:1},{skill:"Intravenous (IV) Infusion",emt:0,aemt:0,pm:1},{skill:"Intraosseous (IO)",emt:0,aemt:1,pm:1},{skill:"Topical / Dermal",emt:0,aemt:0,pm:1}],
trauma:[{skill:"Hemorrhage Control — Direct Pressure",emt:1,aemt:1,pm:1},{skill:"Tourniquet Application",emt:1,aemt:1,pm:1},{skill:"Wound Packing",emt:1,aemt:1,pm:1},{skill:"Chest Seal — Occlusive Dressing",emt:1,aemt:1,pm:1},{skill:"Spinal Motion Restriction",emt:1,aemt:1,pm:1},{skill:"Traction Splint",emt:1,aemt:1,pm:1},{skill:"Physical Restraints",emt:1,aemt:1,pm:1}],
other:[{skill:"Assisted Childbirth",emt:1,aemt:1,pm:1},{skill:"Blood Glucose Monitoring",emt:1,aemt:1,pm:1},{skill:"Wound Irrigation",emt:1,aemt:1,pm:1},{skill:"Phlebotomy",emt:0,aemt:1,pm:1},{skill:"Cincinnati Stroke Screen",emt:1,aemt:1,pm:1}]
};

const OPS_DATA=[
{title:"Air Medical Transport",body:b("Indications",ol(["Critical patients requiring emergent surgical intervention when air is faster than ground","Terrain, traffic, or road conditions make ground impractical","Specialty facility required and air is more expedient","Seasonal conditions: flooding, snowdrifts","MCI — augment ground resources"]))+b("LZ Preparation",ol(["Request helicopter through Communications Center","Continue treating patient per protocol before arrival","Package patients before helicopter arrives — minimize scene time","Law enforcement and fire handle LZ operations"]))},
{title:"MCI Triage — START",body:b("START Triage Categories",'<div class="dose-box" style="border-left-color:#888"><div class="dose-drug" style="color:#aaa">⬛ Black — Expectant / Deceased</div><div class="dose-amount">No respirations after airway repositioning</div></div><div class="dose-box" style="border-left-color:#CC3333"><div class="dose-drug" style="color:#F87070">🔴 Red — Immediate</div><div class="dose-amount">Respirations &gt;30/min, OR no radial pulse, OR fails to follow commands</div></div><div class="dose-box" style="border-left-color:#CC9900"><div class="dose-drug" style="color:#F0C060">🟡 Yellow — Delayed</div><div class="dose-amount">Respirations &lt;30, radial pulse present, follows commands — not immediate threat</div></div><div class="dose-box" style="border-left-color:#2D7A2D"><div class="dose-drug" style="color:#80CC80">🟢 Green — Minor</div><div class="dose-amount">Walking wounded — ambulatory</div></div>')+warn("MCI: treat Black and Green yourself. Red patients first. Only airway repositioning for Black patients in field triage. No CPR during active MCI triage.")},
{title:"Direct Medical Oversight (DMO)",body:b("When to Contact DMO",ul(["Clinical situation exceeds standing order authority","Protocol specifically requires consultation","Clinical uncertainty about appropriate course of action"])+key("When in doubt, contact DMO. Early consultation improves patient outcomes and provides medicolegal protection."))}
];

// ── APP STATE ────────────────────────────────────────────────